### ISSUE TITLE
Add footer to page

### ISSUE THREAD

**Issue by Tiffufu** [Tiffufu/reading-calculator#6]
# Task
Add made with &#10084; & link to Github

# Design Specs

- [ ] Use `#770077` for text color
- [ ] Footer background should be `#FAFAFA`
- [ ] Footer height should use `rem` units for be the equivalent of `height: 200px`
- [ ] Github logo should be [Font Awesome icon](https://fontawesome.com/v5.15/icons/github?style=brands)
- [ ] Github logo should be the same color as text

# Mockup
![Web 1920 – 1](https://user-images.githubusercontent.com/8566039/133175955-f3446abb-8a74-49ca-9148-91e812a26732.png)

**Comment by GowthamPB** [comment]
Can I try working on this? If yes what details should the footer contain?

**Comment by Tiffufu** [comment]
> Can I try working on this? If yes what details should the footer contain?

@GowthamPB Hey sorry I took so long to get back to you! I wanted to give you proper specs. Please see the updated issue for specifications of how to complete this task and let me know if you have any questions.

Thank you so much for offering to help! 😄

**Comment by GowthamPB** [comment]
Hey I am not really sure how I can change the github logo color to #770077

**Comment by GowthamPB** [comment]
![Screenshot_2021-09-16_10-47-05](https://user-images.githubusercontent.com/67544642/133553912-764d0917-09ea-4950-a1f6-577177b62701.png)

**Comment by GowthamPB** [comment]
![Screenshot_2021-09-16_10-58-26](https://user-images.githubusercontent.com/67544642/133554916-fa6014fb-e7ca-494b-bee5-8b86ba99aa9f.png)

**Comment by GowthamPB** [comment]
Right now it looks somewhat like this...

**Comment by andreisavadev** [comment]
Hey,

Pull request sent for this.

Thanks,

**Comment by Tiffufu** [comment]
> Hey,
> 
> Pull request sent for this.
> 
> Thanks,

@andreisavawebdev Thank you for the PR! In the future, I feel like it would be more beneficial if you helped out others who are trying to learn how to accomplish certain things instead of swooping in and submitting a PR. If the issue had become stale, then it's fair game, but Gowtham had been active in this issue no longer than a day ago. Let's help foster a friendly open source community.
